import "./globals.css";
import { UserProvider } from "@/components/UserContext";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { DebugIndicator, DebugModeProvider } from "@/components/DebugMode";
import { DEBUG_MODE_COOKIE } from "@/app/enableDebugMode/common";
import { PublicURLProvider } from "@/components/PublicURLContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const debugMode = cookies().get(DEBUG_MODE_COOKIE)?.value === "true";
  return (
    <html lang="en">
      <body className={inter.className}>
        <PublicURLProvider value={process.env.PUBLIC_URL!}>
          <DebugModeProvider value={debugMode}>
            {children}
            <DebugIndicator />
          </DebugModeProvider>
        </PublicURLProvider>
      </body>
    </html>
  );
}
