import "./globals.css";
import { getCurrentUser } from "@/lib/auth/legacy";
import { UserProvider } from "@/components/UserContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body>
        <UserProvider user={user}>{children}</UserProvider>
      </body>
    </html>
  );
}
