import "./globals.css";
import { UserProvider } from "@/components/UserContext";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { DebugIndicator, DebugModeProvider } from "@/components/DebugMode";
import { DEBUG_MODE_COOKIE } from "@/app/enableDebugMode/route";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const debugMode = cookies().get(DEBUG_MODE_COOKIE)?.value === "true";
  return (
    <html lang="en">
      <body className={inter.className}>
        <DebugModeProvider value={debugMode}>
        <main className="mx-2 max-w-3xl lg:mx-auto">{children}</main>
        <DebugIndicator />
        </DebugModeProvider>
      </body>
    </html>
  );
}
